name: DockerHub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_PATH: nstwf/php

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    strategy:
      matrix:
        php_version: ['8.0', '8.1', '8.2', '8.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        run: echo ${{ secrets.DOCKER_BUILD_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker images
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_PATH }}:fpm-${{ matrix.php_version }} --build-arg PHP_VERSION=${{ matrix.php_version }} .
          docker push ${{ env.DOCKER_IMAGE_PATH }}:fpm-${{ matrix.php_version }}
